DOCKER_REGISTRY_COMPONENTS := yiannisgkoufas
PULL_COMPONENTS := false

DOCKER_REGISTRY_SIDECARS := quay.io/k8scsi
PULL_SIDECARS := true

DATASET_OPERATOR_NAMESPACE := default
NAMESPACES_TO_MONITOR := default

EXTERNAL_PROVISIONER_TAG := v1.4.0

EXTERNAL_ATTACHER_TAG := v1.2.1
#tested in ppc64le v1.0.1

NODE_DRIVER_REGISTRAR_TAG := v1.1.0
#tested in ppc64le v1.0.2

include release-tools/Makefile