site_name: Datashim
repo_url: https://github.com/datashim-io/datashim
repo_name: datashim-io/datashim
theme:
  name: material
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - include-markdown:
      preserve_includer_indent: false
      heading_offset: 1
nav:
  - Introduction: index.md
  - Use cases: use-cases.md
  - Feature Showcase: feature-showcase.md
  - Advanced Usage: advanced-usage.md
  - Kubeflow:
      - Model Storing and Serving: kubeflow/Model-Storing-and-Serving-with-DLF.md
      - Data Volumes for Notebook Servers: kubeflow/Data-Volumes-for-Notebook-Servers.md
      - PVCs for Pipelines SDK: kubeflow/PVCs-for-Pipelines-SDK.md
  - Roadmap: Roadmap.md
  - FAQ: FAQ.md
