site_name: Datashim
repo_url: https://github.com/datashim-io/datashim
repo_name: datashim-io/datashim
theme:
  name: material
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
nav:
  - Introduction: index.md
  - FAQ: FAQ.md
  - Kubeflow:
      - Model Storing and Serving: kubeflow/Model-Storing-and-Serving-with-DLF.md
      - Data Volumes for Notebook Servers: kubeflow/Data-Volumes-for-Notebook-Servers.md
      - PVCs for Pipelines SDK: kubeflow/PVCs-for-Pipelines-SDK.md
  - Ceph Caching: Ceph-Caching.md
  - Archive-based Datasets: Archive-based-Datasets.md
  - Roadmap: Roadmap.md
