apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: model-weights
  namespace: development
spec:
  local:
    bucket: my-model-development
    endpoint: https://s3.us-east.cloud-object-storage.appdomain.cloud
    secret-name: my-model-development-credentials
    type: COS