apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data
    env:
      - name: "MINIO_ROOT_USER"
        value: "ACCESS_KEY"
      - name: "MINIO_ROOT_PASSWORD"
        value: "SECRET_KEY"
    volumeMounts:
    - mountPath: /data
      name: data
    ports:
    - containerPort: 9000
      name: api
  volumes:
  - name: data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9000